# Generated by Django 4.1.2 on 2022-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=150, verbose_name='Colour')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ticket', models.CharField(max_length=150, verbose_name='Order number')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity of cars')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Date of order')),
                ('car', models.ManyToManyField(to='apiord.car', verbose_name='Brand')),
                ('colour', models.ManyToManyField(to='apiord.colour', verbose_name='Colour')),
                ('model', models.ManyToManyField(to='apiord.carsmodel', verbose_name='Model')),
            ],
        ),
    ]
