# Generated by Django 4.1.2 on 2022-10-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='car',
            field=models.ManyToManyField(to='apiord.car'),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='model',
            field=models.CharField(max_length=150, null=True, verbose_name='Model'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.AddField(
            model_name='order',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apiord.colour', verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='apiord.carsmodel', verbose_name='Model'),
            preserve_default=False,
        ),
    ]
