# Generated by Django 4.1.2 on 2022-10-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0002_remove_order_car_carsmodel_car_alter_carsmodel_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='apiord.car', verbose_name='Model'),
            preserve_default=False,
        ),
    ]
