# Generated by Django 4.1.2 on 2022-10-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0003_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_ticket',
        ),
    ]
