# Generated by Django 4.1.2 on 2022-10-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0004_remove_order_order_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
    ]
