# Generated by Django 4.1.2 on 2022-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0005_remove_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ManyToManyField(to='apiord.carsmodel'),
        ),
    ]
