# Generated by Django 4.1.2 on 2022-10-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiord', '0006_remove_carsmodel_car_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='apiord.car'),
            preserve_default=False,
        ),
    ]
