version: '3'

services:
  db:
    image: postgres:13
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xsw2345qwer
      POSTGRES_DB: jango

  backend:
    build: ./
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db